### ISSUE TITLE
More details for strongly gendered languages

### ISSUE THREAD

**Issue by mirrorshot** [usetrmnl/localizations#15]
Languages like Italian have a strong dependency on the gender of words (even referred to objects) to define the writing of many words, even verbs and adjectives many times.

It would be nice to have more references for where the text keys are used.

**Comment by ryanckulp** [comment]
hey Daniele, did you see our annotated screenshots for help with context? 
https://github.com/usetrmnl/localizations/blob/master/GUIDE.md

i can also get you access to a beta account to click around the UI yourself. feel free to email team@usetrmnl.com.

in any case, thanks for the PR! we're wrapping up a plugins marketplace feature first, then adding the last submissions into master all together.

**Comment by mirrorshot** [comment]
I've started from there, but some labels seem not present in the screenshots.
For example "view" to me can have many different meanings from a tech perspective and so many different translations in Italian.

I'll try to get in touch for a beta account, thank you for the offer.
